#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SERVICES
#=================================================

ynh_systemctl --service="$app" --action=stop
ynh_systemctl --service="$app-render" --action=stop

#=================================================
# REMOVE APP SOURCE AND BUILT ARTIFACTS
#=================================================

ynh_safe_rm "$install_dir"

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================

ynh_config_remove_systemd "$app-render"
ynh_config_remove_systemd "$app"
ynh_config_remove_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
